import { ArrowRight, Check, ChevronDown, Clock3, MessageSquareText, Play, ShieldCheck, Star, TrendingUp, Zap } from "lucide-react";

const industries = ["Roofing","Tree Services","HVAC","Plumbing","Electrical","Landscaping","Cleaning","Pest Control"];
const steps = [
  {number:"01",title:"The job gets completed",text:"Your team finishes the work. Presencio can trigger the review workflow automatically.",icon:Check},
  {number:"02",title:"The customer gets asked",text:"A simple SMS or email request goes out while the experience is still fresh.",icon:MessageSquareText},
  {number:"03",title:"We follow up",text:"If they do not respond, the system sends a helpful nudge instead of letting the opportunity disappear.",icon:Clock3},
  {number:"04",title:"You see the results",text:"Happy customers are encouraged to leave feedback, while responses needing nuance stay human.",icon:TrendingUp}
];
const faqs = [
  {q:"Will this replace my team?",a:"No. Presencio automates the repetitive parts of the review process and keeps a human in the loop when a response needs judgment."},
  {q:"Do I need to learn complicated software?",a:"No. The goal is to make the workflow run quietly in the background so you and your team can focus on the business."},
  {q:"Can this work with my current CRM?",a:"In many cases, yes. The exact setup depends on the systems you already use. We map the workflow during the audit."},
  {q:"How much does it cost?",a:"We keep the initial offer simple and tailored to the business. Start with a free review audit and we will show you what we would automate."}
];

export default function Home() {
 return <main>
  <nav className="nav"><a href="#" className="brand"><img src="/logo.svg" className="site-logo" alt="Presencio"/></a><div className="nav-links"><a href="#how-it-works">How it works</a><a href="#results">Why it matters</a><a href="#faq">FAQ</a></div><a href="#audit" className="nav-cta">Get free audit <ArrowRight size={16}/></a></nav>
  <section className="hero"><div className="hero-glow"/><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="pulse"/> AI-powered review automation for local businesses</div><h1>Turn happy customers into <span>5-star reviews.</span></h1><p className="hero-sub">Presencio automates your review requests and follow-ups so your team gets more feedback, more trust, and more opportunities to win the next customer.</p><div className="hero-actions"><a href="#audit" className="button button-primary">Get a free review audit <ArrowRight size={18}/></a><a href="#how-it-works" className="button button-secondary"><Play size={17} fill="currentColor"/> See how it works</a></div><div className="trust-row"><div><ShieldCheck size={17}/> No long-term commitment</div><div><Zap size={17}/> Built around your workflow</div></div></div>
  <div className="dashboard-card"><div className="dashboard-top"><div><div className="muted">Review performance</div><strong>Last 30 days</strong></div><span className="status"><span className="status-dot"/> Automated</span></div><div className="rating"><div className="rating-number">4.9</div><div><div className="stars">{[1,2,3,4,5].map(i=><Star key={i} size={18} fill="currentColor"/>)}</div><div className="muted">Google rating</div></div></div><div className="metric-grid"><div><span>Requests sent</span><strong>148</strong><small>↑ 32%</small></div><div><span>New reviews</span><strong>37</strong><small>↑ 24%</small></div></div><div className="activity"><div className="activity-head"><span>Recent activity</span><span>Live</span></div>{["Review request sent","Customer follow-up sent","New 5-star review"].map((x,i)=><div className="activity-row" key={x}><span className="activity-icon">{i===2?<Star size={14} fill="currentColor"/>:<MessageSquareText size={14}/>}</span><span>{x}</span><span className="activity-time">{i+2}m</span></div>)}</div></div></div><div className="scroll-cue">Scroll to see how it works <span>↓</span></div></section>
  <section className="logo-strip"><div className="container"><span>BUILT FOR BUSINESSES WHERE REPUTATION DRIVES REVENUE</span><div className="industry-list">{industries.map(x=><span key={x}>{x}</span>)}</div></div></section>
  <section className="section" id="how-it-works"><div className="container"><div className="section-heading"><div className="eyebrow">HOW IT WORKS</div><h2>Your review process, <span>on autopilot.</span></h2><p>We remove the repetitive chasing from your team's day without removing the human touch.</p></div><div className="steps">{steps.map(({number,title,text,icon:Icon})=><article className="step-card" key={number}><div className="step-number">{number}</div><div className="step-icon"><Icon size={22}/></div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
  <section className="section dark-section" id="results"><div className="container results-grid"><div><div className="eyebrow light">WHY IT MATTERS</div><h2>Your reputation is part of your sales process.</h2><p className="dark-copy">People compare local businesses before they call. A consistent flow of genuine customer feedback gives prospects another reason to choose you.</p><div className="check-list">{["Ask every customer consistently","Follow up without your staff remembering","Make the process simple for customers","Keep nuanced responses human"].map(x=><div key={x}><span><Check size={15}/></span>{x}</div>)}</div></div><div className="stat-card"><div className="stat-label">THE GOAL</div><div className="big-stat">More trust.</div><div className="big-stat">More calls.</div><div className="big-stat">Less chasing.</div><div className="stat-footer"><Zap size={17}/> Automation that supports your team.</div></div></div></section>
  <section className="section audit-section" id="audit"><div className="container audit-card"><div className="audit-copy"><div className="eyebrow">FREE REVIEW AUDIT</div><h2>Let's find the easiest wins in your review process.</h2><p>We'll look at your current review profile and show you where automation could save time and create more opportunities for feedback.</p><div className="audit-points"><span><Check size={15}/> Review profile check</span><span><Check size={15}/> Request-flow recommendations</span><span><Check size={15}/> Simple automation plan</span></div></div><form className="audit-form" action="https://formspree.io/f/mwlelzqz" method="POST"><input type="hidden" name="_subject" value="New Presencio Free Review Audit Request"/><label>Business name<input name="business" placeholder="Your business" required/></label><label>Your name<input name="name" placeholder="Your name" required/></label><label>Email<input name="email" type="email" placeholder="you@business.com" required/></label><label>Google Business Profile<input name="google" placeholder="Paste your Google profile link"/></label><input name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" style={{display:"none"}}/><button className="button button-primary" type="submit">Request my free audit <ArrowRight size={17}/></button><small>Your information is sent securely.</small></form></div></section>
  <section className="section faq-section" id="faq"><div className="container faq-grid"><div><div className="eyebrow">FAQ</div><h2>Questions, answered.</h2><p>Still unsure? Start with the free audit and we'll make the setup specific to your business.</p></div><div className="faq-list">{faqs.map(f=><details key={f.q}><summary>{f.q}<ChevronDown size={18}/></summary><p>{f.a}</p></details>)}</div></div></section>
  <section className="final-cta"><div className="container"><div className="eyebrow light">READY TO GET STARTED?</div><h2>Stop hoping customers remember to leave a review.</h2><p>Build a process that asks consistently, follows up automatically, and keeps your team focused on the work.</p><a href="#audit" className="button button-light">Get your free audit <ArrowRight size={18}/></a></div></section>
  <footer><div className="container footer-inner"><div className="brand"><img src="/logo.svg" className="site-logo footer-logo" alt="Presencio"/></div><p>AI growth systems for local businesses.</p><span>© 2026 Presencio</span></div></footer>
 </main>;
}