import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, Clock3, MapPin, Phone, ShieldCheck, Star } from "lucide-react";

const data: Record<string, { type:string; name:string; city:string; phone:string; tagline:string; services:string[]; accent:string }> = {
  "apexflow-plumbing": { type:"PLUMBING", name:"ApexFlow Plumbing", city:"Dallas, TX", phone:"(214) 555-0148", tagline:"Fast, reliable plumbing when you need it most.", services:["Emergency plumbing","Drain cleaning","Water heater repair","Leak detection","Fixture installation","Sewer services"], accent:"plumb" },
  "summit-ridge-roofing": { type:"ROOFING", name:"Summit Ridge Roofing", city:"Phoenix, AZ", phone:"(602) 555-0184", tagline:"A stronger roof starts with a better plan.", services:["Roof inspections","Roof replacement","Storm damage","Repairs","Commercial roofing","Financing options"], accent:"roof" },
  "blackline-auto-detail": { type:"AUTO DETAILING", name:"Blackline Auto Detail", city:"Tampa, FL", phone:"(813) 555-0117", tagline:"Your car. Better than new.", services:["Interior detailing","Exterior detail","Paint correction","Ceramic coating","Maintenance plans","Fleet detailing"], accent:"auto" },
  "northstar-hvac": { type:"HVAC", name:"Northstar HVAC", city:"Charlotte, NC", phone:"(704) 555-0162", tagline:"Comfort you can count on, day or night.", services:["AC repair","Heating service","HVAC installation","Maintenance plans","Indoor air quality","Emergency service"], accent:"hvac" },
};

export default async function PortfolioSite({ params }: { params: Promise<{ slug:string }> }) {
  const { slug } = await params; const site = data[slug] ?? data["apexflow-plumbing"];
  return <main className={`client-site ${site.accent}`}>
    <header className="client-nav"><Link href="/portfolio" className="client-brand">{site.name}</Link><nav><a href="#services">Services</a><a href="#why">Why us</a><a href="#contact">Contact</a></nav><a className="client-call" href={`tel:${site.phone.replace(/[^0-9]/g,"")}`}><Phone size={15}/> Call now</a></header>
    <section className="client-hero"><div className="client-hero-copy"><div className="client-kicker"><MapPin size={13}/> {site.city} · {site.type}</div><h1>{site.tagline}</h1><p>Professional local service with clear communication, dependable workmanship and a team ready to help.</p><div className="client-actions"><a className="client-primary" href={`tel:${site.phone.replace(/[^0-9]/g,"")}`}>Call {site.phone} <Phone size={16}/></a><a className="client-secondary" href="#contact">Request a free quote <ArrowRight size={16}/></a></div><div className="client-trust"><span><ShieldCheck size={15}/> Local & dependable</span><span><Star size={15} fill="currentColor"/> 5-star experience</span><span><Clock3 size={15}/> Fast response</span></div></div><div className="client-visual"><div className="visual-card"><span>LOCAL SERVICE</span><strong>Quality work.<br/><em>Clear communication.</em></strong><div className="visual-stars">★★★★★ <small>Customer-first service</small></div></div></div></section>
    <section className="client-strip"><span>PROUDLY SERVING {site.city.toUpperCase()}</span><span>LICENSED & PROFESSIONAL</span><span>FREE ESTIMATES</span></section>
    <section className="client-section" id="services"><div className="client-container"><div className="client-heading"><small>OUR SERVICES</small><h2>Everything you need. <em>Done right.</em></h2><p>Simple, professional service without the runaround.</p></div><div className="client-services">{site.services.map((s,i)=><article key={s}><span>0{i+1}</span><h3>{s}</h3><p>Professional service tailored to your property, vehicle or business.</p><a href="#contact">Learn more <ArrowRight size={14}/></a></article>)}</div></div></section>
    <section className="client-proof" id="why"><div className="client-container client-proof-grid"><div><small>WHY CUSTOMERS CHOOSE US</small><h2>Professional from the first call to the final check.</h2></div><div className="proof-list"><div><Check/><strong>Clear pricing</strong><span>No confusing surprises.</span></div><div><Check/><strong>Quality workmanship</strong><span>Built around doing the job properly.</span></div><div><Check/><strong>Easy communication</strong><span>Fast answers when you need them.</span></div></div></div></section>
    <section className="client-contact" id="contact"><div className="client-container"><div><small>READY TO GET STARTED?</small><h2>Let's take care of it.</h2><p>Tell us what you need and we'll help you figure out the next step.</p></div><div className="client-contact-card"><strong>Request a free quote</strong><a href={`tel:${site.phone.replace(/[^0-9]/g,"")}`}>{site.phone}</a><a className="client-primary" href={`tel:${site.phone.replace(/[^0-9]/g,"")}`}>Call now <Phone size={15}/></a></div></div></section>
    <footer className="client-footer"><div>{site.name}</div><span>{site.city} · {site.type}</span><Link href="/portfolio"><ArrowLeft size={14}/> Back to Presencio Portfolio</Link></footer>
  </main>;
}
