import Link from "next/link";
import { ArrowRight } from "lucide-react";

const sites = [
  { slug: "apexflow-plumbing", type: "PLUMBING", name: "ApexFlow Plumbing", location: "Dallas, TX", text: "Emergency plumbing website focused on calls, quote requests and service-area coverage." },
  { slug: "summit-ridge-roofing", type: "ROOFING", name: "Summit Ridge Roofing", location: "Phoenix, AZ", text: "Trust-first roofing experience built around inspections, financing and project enquiries." },
  { slug: "blackline-auto-detail", type: "AUTO DETAILING", name: "Blackline Auto Detail", location: "Tampa, FL", text: "Premium detailing site designed to showcase packages and drive bookings." },
  { slug: "northstar-hvac", type: "HVAC", name: "Northstar HVAC", location: "Charlotte, NC", text: "Conversion-focused HVAC website with service coverage and rapid-contact CTAs." },
];

export default function Portfolio() {
  return <main className="portfolio-page">
    <style>{`.portfolio-page{min-height:100vh;background:#f7f7fa;color:#0b0c10}.portfolio-nav{height:78px;display:flex;align-items:center;justify-content:space-between;width:min(1240px,calc(100% - 40px));margin:auto}.portfolio-hero{padding:105px 0 85px;background:radial-gradient(circle at 75% 30%,rgba(112,92,255,.16),transparent 30%),linear-gradient(180deg,#fbfbff,#f7f7fa);border-bottom:1px solid #e5e6eb}.portfolio-hero h1{max-width:850px}.portfolio-hero p{max-width:650px;color:#69707d;font-size:17px;line-height:1.7}.portfolio-detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}.portfolio-showcase{background:#fff;border:1px solid #e1e2e8;border-radius:22px;overflow:hidden;box-shadow:0 10px 35px rgba(20,21,35,.05);transition:.25s}.portfolio-showcase:hover{transform:translateY(-7px);box-shadow:0 30px 70px rgba(20,21,35,.11)}.showcase-screen{height:330px;padding:18px;background:linear-gradient(145deg,#eeeaff,#fff)}.showcase-2{background:linear-gradient(145deg,#eaf2ff,#fff)}.showcase-3{background:linear-gradient(145deg,#fff0e5,#fff)}.showcase-4{background:linear-gradient(145deg,#e5faf6,#fff)}.showcase-top{height:30px;border:1px solid rgba(20,21,30,.08);background:rgba(255,255,255,.78);border-radius:8px;display:flex;align-items:center;gap:5px;padding:0 10px}.showcase-top i{width:5px;height:5px;border-radius:50%;background:#c6c8cf}.showcase-top span{font-size:8px;color:#777d88;margin-left:8px}.showcase-copy{padding:70px 38px 0}.showcase-copy small{font-size:8px;font-weight:900;letter-spacing:.16em;color:#705cff}.showcase-copy strong{display:block;font-size:48px;line-height:.88;letter-spacing:-.07em;margin:14px 0 26px}.showcase-copy em{font-style:normal;color:#705cff}.showcase-copy>span{display:inline-block;background:#0b0c10;color:#fff;padding:11px 14px;border-radius:7px;font-size:9px;font-weight:800}.showcase-info{padding:27px 28px 30px}.showcase-info>div{display:flex;gap:12px;align-items:center}.showcase-info b{font-size:8px;letter-spacing:.14em;color:#705cff}.showcase-info small{font-size:9px;color:#969aa3}.showcase-info h2{font-size:26px;letter-spacing:-.05em;margin:10px 0 8px}.showcase-info p{color:#717782;font-size:12px;line-height:1.65;margin:0}.showcase-info .text-link{margin-top:18px}.portfolio-page .final-cta{margin-top:60px}@media(max-width:800px){.portfolio-detail-grid{grid-template-columns:1fr}.showcase-copy{padding-top:55px}.showcase-copy strong{font-size:40px}.portfolio-nav{padding:0 5px}.portfolio-hero{padding-top:70px}}`}</style>
    <nav className="portfolio-nav"><Link href="/" className="brand"><img src="/logo.svg" className="site-logo" alt="Presencio" /></Link><Link href="/" className="button button-primary">Back to Presencio <ArrowRight size={16}/></Link></nav>
    <section className="portfolio-hero"><div className="container"><div className="eyebrow">PRESENCIO PORTFOLIO</div><h1>Websites designed to <span>win the local customer.</span></h1><p>Explore complete examples of the websites Presencio builds for service businesses. Each concept is structured around trust, clarity and conversion.</p></div></section>
    <section className="section"><div className="container"><div className="portfolio-detail-grid">{sites.map((site, i) => <Link href={`/portfolio/${site.slug}`} className="portfolio-showcase" key={site.slug}><div className={`showcase-screen showcase-${i+1}`}><div className="showcase-top"><i/><i/><i/><span>{site.name.toLowerCase().replaceAll(" ","")}.com</span></div><div className="showcase-copy"><small>{site.type}</small><strong>{site.name.split(" ")[0]}<br/><em>{site.name.split(" ").slice(1).join(" ")}</em></strong><span>Get a Free Quote →</span></div></div><div className="showcase-info"><div><b>{site.type}</b><small>{site.location}</small></div><h2>{site.name}</h2><p>{site.text}</p><span className="text-link">View full website <ArrowRight size={15}/></span></div></Link>)}</div></div></section>
    <section className="final-cta"><div className="container"><div className="eyebrow light">YOUR BUSINESS NEXT</div><h2>Want a site like these?</h2><p>We'll build around your services, service area and the action you want customers to take.</p><Link href="/#audit" className="button button-light">Get a free business audit <ArrowRight size={17}/></Link></div></section>
  </main>;
}
