import { NextResponse } from 'next/server';
import { z } from 'zod';
import { requireUser } from '../../../lib/problemsolved/auth';
import { db, logAudit } from '../../../lib/problemsolved/db';
import { totalScore, validateScore, type ScoreBreakdown } from '../../../lib/problemsolved/types';

const schema = z.object({
  problem:z.string().min(8), targetCustomer:z.string().min(3), severity:z.string().default('unknown'), currentWorkaround:z.string().optional(),
  researchBurdenHours:z.number().nonnegative().optional(), moneyAlreadySpent:z.number().nonnegative().optional(), consequences:z.string().optional(), pdfConcept:z.string().optional(), estimatedWtp:z.number().nonnegative().optional(), confidence:z.number().min(0).max(1).default(.5),
  scores:z.object({ pain:z.number(), financialConsequence:z.number(), researchBurden:z.number(), demandEvidence:z.number(), existingSpending:z.number(), informationFragmentation:z.number(), pdfSuitability:z.number(), reachability:z.number() })
});
export async function GET() { try { await requireUser(); const rows = await db()`SELECT id, problem, target_customer, commercial_score, status, confidence, created_at FROM opportunities ORDER BY commercial_score DESC, created_at DESC LIMIT 100`; return NextResponse.json({ opportunities:rows }); } catch(e) { return NextResponse.json({error:e instanceof Error?e.message:'Unknown error'}, {status:e instanceof Error && e.message==='UNAUTHORIZED'?401:500}); } }
export async function POST(req:Request) { try { const actor=await requireUser(); const b=schema.safeParse(await req.json().catch(()=>null)); if(!b.success) return NextResponse.json({error:b.error.issues},{status:400}); const s=b.data.scores as ScoreBreakdown; validateScore(s); const score=totalScore(s); const rows=await db()`INSERT INTO opportunities (problem,target_customer,severity,current_workaround,research_burden_hours,money_already_spent,consequences,pdf_concept,estimated_wtp,confidence,pain_score,financial_consequence_score,research_burden_score,demand_evidence_score,existing_spending_score,information_fragmentation_score,pdf_suitability_score,reachability_score,commercial_score) VALUES (${b.data.problem},${b.data.targetCustomer},${b.data.severity},${b.data.currentWorkaround??null},${b.data.researchBurdenHours??null},${b.data.moneyAlreadySpent??null},${b.data.consequences??null},${b.data.pdfConcept??null},${b.data.estimatedWtp??null},${b.data.confidence},${s.pain},${s.financialConsequence},${s.researchBurden},${s.demandEvidence},${s.existingSpending},${s.informationFragmentation},${s.pdfSuitability},${s.reachability},${score}) RETURNING id, status, commercial_score`; await logAudit(actor,'OPPORTUNITY_CREATED','opportunity',rows[0].id,{score}); return NextResponse.json(rows[0],{status:201}); } catch(e) { return NextResponse.json({error:e instanceof Error?e.message:'Unknown error'},{status:e instanceof Error&&e.message==='UNAUTHORIZED'?401:500}); } }
